# Generated by Django 4.2.3 on 2023-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('timeperiod', models.CharField(max_length=50)),
                ('expenses', models.IntegerField(max_length=20)),
            ],
        ),
    ]
