# Generated by Django 4.2.3 on 2023-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_workers_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('totexp', models.CharField(max_length=50)),
                ('projloc', models.CharField(max_length=50)),
                ('amtsac', models.CharField(max_length=50)),
            ],
        ),
    ]
