# Generated by Django 4.2.3 on 2023-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roadtype', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('lanes', models.CharField(max_length=50)),
                ('budget', models.CharField(default=True, max_length=50, null=True)),
            ],
        ),
    ]
